document.getElementById('add-money').addEventListener('click',function()
    {
        hide('add-container');
    }
)
document.getElementById('cash-out').addEventListener('click',function()
    {
        hide('cash-container');
    }
)
document.getElementById('transfer-money').addEventListener('click',function()
    {
        hide('transfer-container');
    }
)
document.getElementById('get-bonus').addEventListener('click',function()
    {
        hide('bonus-container');
    }
)
document.getElementById('pay-bill').addEventListener('click',function()
    {
        hide('pay-bill-container');
    }
)
document.getElementById('transactions').addEventListener('click',function()
    {
        hide('transactions-container');
    }
)